name: Spring security
rating: 5
imageUrl: https://github.com/msa-ez/template-spring-boot-3/assets/123912988/05f2d75a-86d7-4cf7-a328-5236190dd883
templateName: spring-security
description: Spring security description
